Tensor Field Networks

Implementation of shape classification demonstration

In [1]:
%load_ext autoreload
%autoreload 2

In [7]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as anim
import torch 
import random
from math import pi, sqrt
import tensorfieldnetworks.layers as layers
import tensorfieldnetworks.utils as utils
from tensorfieldnetworks.utils import FLOAT_TYPE

tetris = [[(0, 0, 0), (0, 0, 1), (1, 0, 0), (1, 1, 0)],  # chiral_shape_1
          [(0, 0, 0), (0, 0, 1), (1, 0, 0), (1, -1, 0)], # chiral_shape_2
          [(0, 0, 0), (1, 0, 0), (0, 1, 0), (1, 1, 0)],  # square
          [(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 0, 3)],  # line
          [(0, 0, 0), (0, 0, 1), (0, 1, 0), (1, 0, 0)],  # corner
          [(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0)],  # T
          [(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 1)],  # zigzag
          [(0, 0, 0), (1, 0, 0), (1, 1, 0), (2, 1, 0)]]  # L

dataset = [np.array(points_) for points_ in tetris]
num_classes = len(dataset)

In [8]:
# radial basis functions
rbf_low = 0.0
rbf_high = 3.5
rbf_count = 4
rbf_spacing = (rbf_high - rbf_low) / rbf_count
centers = torch.Tensor(np.linspace(rbf_low, rbf_high, rbf_count))

In [9]:
def get_inputs(r):
    
    # rij : [N, N, 3]
    rij = utils.difference_matrix(r)

    # dij : [N, N]
    dij = utils.distance_matrix(r)

    # rbf : [N, N, rbf_count]
    gamma = 1. / rbf_spacing
    rbf = torch.exp(-gamma * (dij.unsqueeze(-1) - centers)**2)
    
    return rij, dij, rbf

In [36]:
class Readout(torch.nn.Module):
    
    def __init__(self, input_dims, num_classes):
        super(Readout, self).__init__()
        
        self.lin = torch.nn.Linear(input_dims, num_classes,)
        self.input_dims = input_dims
        self.num_classes = num_classes
        
    def forward(self, inputs):
        inputs = torch.mean(inputs.squeeze(),dim=0)
#         print(inputs)
        inputs = self.lin.forward(inputs).unsqueeze(0)
        return inputs
        
        
class TetrisNetwork(torch.nn.Module):
    
    def __init__(self, rbf_dim = rbf_count, num_classes = num_classes):
        super(TetrisNetwork, self).__init__()
        self.layer_dims = [1, 4, 4, 4]
#         self.layer_dims = [1,4]
        self.num_layers = len(self.layer_dims) - 1  
        self.rbf_dim = rbf_dim
        self.embed = layers.SelfInteractionLayer(input_dim = 1, output_dim = 1, bias = False)
    
        self.layers = []
        for layer, (layer_dim_out, layer_dim_in) in enumerate(zip(self.layer_dims[1:], self.layer_dims[:-1])):
            self.layers.append(layers.Convolution(rbf_dim, layer_dim_in))
            self.layers.append(layers.Concatenation())
            self.layers.append(layers.SelfInteraction(layer_dim_in, layer_dim_out))
            self.layers.append(layers.NonLinearity(layer_dim_out))
        self.layers = torch.nn.ModuleList(self.layers)
        self.ones = torch.ones(4,1,1)
        self.readout = Readout(self.layer_dims[-1], num_classes)
        
    def forward(self, rbf, rij):
    
        embed = self.embed(self.ones)       
        input_tensor_list = {0: [embed]}
        for il, layer in enumerate(self.layers[::4]):
            input_tensor_list = self.layers[4*il](input_tensor_list, rbf, rij) #Convolution
#             if il == 1:
#                 print(input_tensor_list[0][0])
#                 print(input_tensor_list[0][1])
            input_tensor_list = self.layers[4*il+1](input_tensor_list) # Concatenation
#             if il == 0:
#                 print(input_tensor_list[1][0])
            input_tensor_list = self.layers[4*il+2](input_tensor_list) # Self interaction
#             if il == 2:
#                 print(input_tensor_list[0][0])
            input_tensor_list = self.layers[4*il+3](input_tensor_list) # Nonlinearity
#             if il == 1:
#                 print(input_tensor_list[0][0])
        return self.readout(input_tensor_list[0][0])

In [69]:
tetris_tensor = torch.Tensor(tetris)
rbf_list = []
rij_list = []
for t in tetris_tensor:
    rbf_list.append(get_inputs(t)[2])
    rij_list.append(get_inputs(t)[0])

labels = torch.LongTensor(np.arange(len(tetris_tensor))).view(-1,1)

In [70]:
model = TetrisNetwork()

# model.embed(model.ones)

In [71]:
i = 0
# label = labels[i]
rij, rbf = rij_list[i], rbf_list[i]
# zero the parameter gradients
# optimizer.zero_grad()
outputs = model(rbf, rij)
print(outputs)

tensor([[ 0.3245,  0.0535, -0.4324,  0.3475,  0.0816,  0.3117,  0.4078,  0.3294]],
       grad_fn=<UnsqueezeBackward0>)


In [72]:
import torch.optim as optim

criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [ ]:
for epoch in range(2001):  # loop over the dataset multiple times
# for epoch in range(100):  # loop over the dataset multiple times
    running_loss = 0.0
    order = np.arange(len(tetris_tensor))
#     np.random.shuffle(order)
    for i in order:
        
        label = labels[i]
        rij, rbf = rij_list[i], rbf_list[i]
        # zero the parameter gradients
        optimizer.zero_grad()
        outputs = model(rbf, rij)
        loss = criterion(outputs, label)
   
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    
    if epoch%100 == 0:
        print('{:3.3f}'.format(running_loss/len(tetris_tensor)))
print('Finished Training')

2.134
1.061
0.488
0.133
0.053
0.033
0.014
0.007
0.004
0.003
1.215
1.168
0.855
0.576
0.475
0.431
0.400


In [60]:
rng = np.random.RandomState()
test_set_size = 25
predictions = [list() for i in range(len(dataset))]

correct_predictions = 0
total_predictions = 0
for i in range(test_set_size):
    for label, shape in enumerate(dataset):
        rotation = utils.random_rotation_matrix(rng)
        rotated_shape = np.dot(shape, rotation)
        translation = np.expand_dims(np.random.uniform(low=-3., high=3., size=(3)), axis=0)
        translated_shape = rotated_shape + translation
        rij, dij, rbf = get_inputs(torch.Tensor(translated_shape))
        
        outputs = model(rbf, rij)
        output_label = torch.argmax(outputs)
        total_predictions += 1
        if output_label == label:
            correct_predictions += 1
#         else:
#             print(output_label)
#             print(label)
print('Test accuracy: %f' % (float(correct_predictions) / total_predictions))

Test accuracy: 1.000000


In [61]:
rng = np.random.RandomState()
test_set_size = 25
predictions = [list() for i in range(len(dataset))]

correct_predictions = 0
total_predictions = 0

for label, shape in enumerate(dataset):
    rij, dij, rbf = get_inputs(torch.Tensor(shape))
    fixed_output = model(rbf, rij)
#     fixed_label = torch.argmax(outputs)
    for i in range(test_set_size):
        rotation = utils.random_rotation_matrix(rng)
        rotated_shape = np.dot(shape, rotation)
        translation = np.expand_dims(np.random.uniform(low=-3., high=3., size=(3)), axis=0)
        translated_shape = rotated_shape + translation
        rij, dij, rbf = get_inputs(torch.Tensor(translated_shape))

        outputs = model(rbf, rij)
        output_label = torch.argmax(outputs)
        total_predictions += 1
        if np.allclose(outputs.detach().numpy(),fixed_output.detach().numpy(), rtol=1e-5, atol = 1e-5):
            correct_predictions += 1
        else:
            print('=============')
            print(outputs)
            print(fixed_output)
print('Invariant accuracy: %f' % (float(correct_predictions) / total_predictions))

tensor([[  39.3212,   54.6896,   40.8027,    0.9964, -191.7429,   31.0737,
            2.3399,   34.9450]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3211,   54.6895,   40.8026,    0.9963, -191.7426,   31.0736,
            2.3398,   34.9449]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3212,   54.6895,   40.8026,    0.9964, -191.7428,   31.0737,
            2.3399,   34.9450]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3211,   54.6895,   40.8026,    0.9963, -191.7426,   31.0736,
            2.3398,   34.9449]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3211,   54.6895,   40.8026,    0.9963, -191.7424,   31.0736,
            2.3398,   34.9449]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3211,   54.6895,   40.8026,    0.9963, -191.7426,   31.0736,
            2.3398,   34.9449]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3212,   54.6895,   40.8026,    0.9963, -191.7427,   31.0737,
            2.3398,   34.9450]], grad_fn=<UnsqueezeBackward0>)
tensor([[  39.3211,   54.6895,   4